name: build

on:
  push:
    branches: [ $default-branch, develop ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for Library
      run: dotnet restore .\src\Uploadino\
    - name: Build
      run: dotnet build .\src\Uploadino\ --no-restore  
    - name: Restore dependencies for tool
      run: dotnet restore .\src\Uploadinator\
    - name: Build tool
      run: dotnet build .\src\Uploadinator\ --no-restore 